<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <style>
        body { font-family: Helvetica, Arial, sans-serif; color: #1d1d1f; padding: 30px; }
        .header { border-bottom: 3px solid #534AB7; padding-bottom: 16px; margin-bottom: 24px; }
        .logo { font-size: 20px; font-weight: bold; color: #534AB7; }
        .title { font-size: 22px; font-weight: bold; margin-top: 14px; }
        .subtitle { font-size: 13px; color: #6e6e73; margin-top: 4px; }
        .badge { display: inline-block; padding: 3px 10px; border-radius: 4px; font-size: 11px; font-weight: bold; background: #eaf3de; color: #3b6d11; }
        .section { margin-top: 24px; }
        .section-title { font-size: 14px; font-weight: bold; color: #534AB7; border-bottom: 1px solid #e5e5ea; padding-bottom: 6px; margin-bottom: 12px; }
        table { width: 100%; border-collapse: collapse; }
        td { padding: 6px 0; font-size: 12px; }
        .label { color: #6e6e73; width: 40%; }
        .value { color: #1d1d1f; font-weight: bold; }
        .footer { margin-top: 40px; font-size: 10px; color: #aaaabc; text-align: center; border-top: 1px solid #e5e5ea; padding-top: 12px; }
    </style>
</head>
<body>
    <div class="header">
        <div class="logo">Veltahr</div>
        <div class="title">{{ $employee->first_name }} {{ $employee->last_name }}</div>
        <div class="subtitle">{{ $employee->position }} &mdash; {{ $employee->department }}</div>
        <span class="badge">{{ $employee->status === 'active' ? 'ACTIVE' : 'ON LEAVE' }}</span>
    </div>

    <div class="section">
        <div class="section-title">Employee Information</div>
        <table>
            <tr><td class="label">Employee ID</td><td class="value">EMP-{{ str_pad($employee->id, 4, '0', STR_PAD_LEFT) }}</td></tr>
            <tr><td class="label">Email</td><td class="value">{{ $employee->email }}</td></tr>
            <tr><td class="label">Phone</td><td class="value">{{ $employee->phone ?? 'N/A' }}</td></tr>
            <tr><td class="label">Department</td><td class="value">{{ $employee->department }}</td></tr>
            <tr><td class="label">Position</td><td class="value">{{ $employee->position }}</td></tr>
            <tr><td class="label">Hire date</td><td class="value">{{ \Carbon\Carbon::parse($employee->hire_date)->format('d M Y') }}</td></tr>
        </table>
    </div>

    <div class="section">
        <div class="section-title">Compensation Summary</div>
        <table>
            <tr><td class="label">Gross salary</td><td class="value">${{ number_format($employee->salary, 2) }}</td></tr>
            <tr><td class="label">Tax (20%)</td><td class="value">-${{ number_format($tax, 2) }}</td></tr>
            <tr><td class="label">Insurance (5%)</td><td class="value">-${{ number_format($insurance, 2) }}</td></tr>
            <tr><td class="label">Net salary</td><td class="value">${{ number_format($net, 2) }}</td></tr>
        </table>
    </div>

    <div class="footer">
        Generated by Veltahr on {{ \Carbon\Carbon::now()->format('d M Y, H:i') }} &mdash; Confidential document.
    </div>
</body>
</html>